title: Aisf Perugia
author: Aisf Perugia
email: perugia@ai-sf.it
#phone: (650) 576-5403
github: https://github.com/davidpelosi21
about: Pagina del comitato locale di Perugia
disqus_shortname: programming
google_analytics: UA-31048387-6
avatar_url: /static/img/me.jpg


social:
    - icon: fa-facebook
      link: "https://www.facebook.com/aisfpg/"
    - icon: fa-instagram
      link: "https://www.instagram.com/aisf_perugia/"

urls:
    - text: Helios
      url: /Helios/
    - text: QFT
      url: /QFT/
    - text: Articoli
      url: /Articoli/
    - text: Download
      url: /Download/
    - text: Corsi Interni
      url: /Corsi/
# url: "http://localhost:4000"
url: "https://davidpelosi21.github.io/"
