- id: "{{ site.url }}"
  title: "AISF Perugia"
  description: "Comitato Locale di Perugia dell'Associazione Italiana Studenti di Fisica."
  keywords: "aisf associazione italiana studenti di fisica perugia physics association students international programme event"
